#!/bin/bash

# 该版预设的账号、密码和端口、直接进入安装去除菜单
user="test886"
pass="test886123"
port="30555"

# 检查是否以root权限执行
if [[ $EUID -ne 0 ]]; then
  echo "请使用root权限运行此脚本"
  exit 1
fi

# 检查操作系统
if [[ ! -f /etc/os-release ]]; then
  echo "无法确定操作系统类型"
  exit 1
fi
source /etc/os-release
if [[ "${ID}" != "centos" || ( "${VERSION_ID}" != "7" && "${VERSION_ID}" != "8" ) ]]; then
  echo "本脚本仅支持CentOS7或8"
  exit 1
fi

# 安装 Socks5
action1() {
if [ ! -f "/usr/local/bin/gost" ]; then
  # 下载配套程序和脚本
  echo "正在下载程序 ..."
  curl -sSL -o /usr/local/bin/gost -L https://raw.githubusercontent.com/tommy08888/ssssss/main/gost
  curl -sSL -o /usr/local/bin/ss5 -L https://raw.githubusercontent.com/tommy08888/ssssss/main/ss5
  curl -sSL -o /usr/local/bin/ss5-start -L https://raw.githubusercontent.com/tommy08888/ssssss/main/ss5-start
  chmod 755 /usr/local/bin/*
  # 把用户输入保存到配置文件
  echo "$user" > /opt/ss5.conf
  echo "$pass" >> /opt/ss5.conf
  echo "$port" >> /opt/ss5.conf
  # 配置计划任务
  echo >> /etc/crontab
  echo "*/1 * * * * root /usr/local/bin/ss5-start" >> /etc/crontab
  # 立即启动 Socks5
  /usr/local/bin/ss5-start
  # 输出配置信息
  echo "Socks5 安装成功连接信息如下"
  echo "注意显示端口为虚拟机内部端口"
  echo "NAT机型要替换为公网IP的端口"
  echo -e "\033[32m终端输 ss5 即可显示管理界面\033[0m"
  ip=$(curl -sS https://api.my-ip.io/ip)
  echo -e
  echo -e "\033[32msocks5://$ip:$port:$user:$pass\033[0m"
  echo -e
  exit
else
  echo "Socks5 已安装配置如下"
  # 读取配置
  conf="/opt/ss5.conf"
  if [ -f "$conf" ]; then
    user=$(sed -n '1p' /opt/ss5.conf)
    pass=$(sed -n '2p' /opt/ss5.conf)
    port=$(sed -n '3p' /opt/ss5.conf)
  else
    echo "配置文件不存在请重新安装"
    exit
  fi
  # 显示当前配置
  ip=$(curl -sS https://api.my-ip.io/ip)
  echo -e
  echo -e "\033[32msocks5://$ip:$port:$user:$pass\033[0m"
  echo -e
  exit
fi
}

# 直接调用安装 Socks5 函数
action1

# 屏蔽邮件提示
>/dev/null 2>&1
